const API_BASE_URL_DEVELOPMENT = "https://localhost:7195";

const ENDPOINTS = {
  GET_ALL_WAREHOUSES: "api/warehouses",
  GET_WAREHOUSE_BY_ID: "api/warehouses/warehousid",
  CREATE_WAREHOUSE: "api/warehouses", //cia ??
  UPDATE_WAREHOUSE: "api/warehouses/warehouseid",
  DELETE_WAREHOUSE_BY_ID: "api/warehouses",
};

const development = {
  API_URL_GET_ALL_WAREHOUSES: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_WAREHOUSES}`,
  API_URL_GET_WAREHOUSE_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_WAREHOUSE_BY_ID}`,
  API_URL_CREATE_WAREHOUSE: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.CREATE_WAREHOUSE}`,
  API_URL_UPDATE_WAREHOUSE: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.UPDATE_WAREHOUSE}`,
  API_URL_DELETE_WAREHOUSE_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.DELETE_WAREHOUSE_BY_ID}`,
};

const Constants = development;
export default Constants;
